[[agents]]
id = 'hApp-agent'
name = 'hAppStore Agent'
keystore_file = 'agent.key'
public_address = 'HcSciA353PAhxu9grqc9SNfwocdqbukjg4wQQVDoodstrpn5E4534FJ45EfD4Ua'

[[dnas]]
id = "happ_store_dna"
file = "hApp-store/dist/hApp-store.dna.json"
hash = "QmUdYaRoNM2wfkBoEHsvqgA9Yp4gaL4xbRcJNscW5fzw5n"

[[instances]]
id = "happ-store"
dna = "happ_store_dna"
agent = "hApp-agent"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "tmp-storage"

[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 4000
[[interfaces.instances]]
id = "happ-store"
