[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcSCIdhnbr43tcajfgmj3NDjj9TB6wbf3Q9nakZcHtc5c5a7KupzRFMSmwvxigi"
keystore_file = "./keystore.key"

[[dnas]]
id = "happ_store_dna"
file = "dna/happ-store.dna.json"
hash = "Qm328wyq38924x"

[[instances]]
id = "happ-store"
dna = "happ_store_dna"
agent = "test_agent1"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "tmp-storage"

[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 4000
[[interfaces.instances]]
id = "happ-store"

[[ui_bundles]]
id = "main"
root_dir = "./ui"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 3000
dna_interface = "websocket_interface"

