version: 2

jobs:
  build:
    docker:
    - image: holochain/holonix:latest
    steps:
    - checkout
    - run:
        name: Starting test
        command: nix-shell --command cd dna-src --run dk-test
